<?php
$_slider['a'] = $this->getBannerSlider(3);
$_slider['b'] = $this->getBannerSlider(4);

function getCategory($_id)
{
	$category = Mage::getModel('catalog/category')->load($_id);
	return $category;
}

function getCategories($_parentId , $_path = 1)
{
	$collection = Mage::getModel('catalog/category')->getCollection()
        ->addAttributeToFilter('is_active', 1) //only active categories
        ->addAttributeToFilter('parent_id', $_parentId);
	
	return $collection;
	//print_r($collection->getItems());exit;
	
}

$_mediaPath = Mage::getBaseUrl('media') . 'themevast/banner/';
//echo $_mediaPath;exit;

$_phoneAccId = 89;
$_phonAcc['parent'] = getCategory($_phoneAccId);
$_phonAcc['sub'] = getCategories($_phoneAccId);

$_phonePartsId = 90;
$_phoneParts['parent'] = getCategory($_phonePartsId);
$_phoneParts['sub'] = getCategories($_phonePartsId);

$_webUrl = Mage::getBaseUrl();
?>

<?php /*?>
<!--Accessory-->
<div class="access-wrapper phone-access">
    <div class="access-content">
        <div class="access-box container">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 clearfix">
                    <div class="kind-Category left">
                        <h4><a href="<?php echo $_phonAcc['parent']->getUrl()?>" title="<?php echo $_phonAcc['parent']->getName()?>"><?php echo $_phonAcc['parent']->getName()?></a></h4>
                        <ul>
                        <?php 
						foreach($_phonAcc['sub'] as $_item):
							$category = getCategory($_item->getId());
						?>
                        <li><a href="<?php echo $category->getUrl()?>" title="<?php echo $category->getName();?>"><?php echo $category->getName();?></a></li>
                        <?php endforeach;?>
                        </ul>
                    </div>
                    <div class="kind-Slide right hidden-xs">
                        <ul class="kind-SlideList">
                        <!-- edit by mivec -->
                        <?php
						//edit by mivec  category slider_a
						if ($_slider['a']):
							foreach ($_slider['a']->getItems() as $_item) :
							//print_r($_item->gettitle());exit;
						?>
                            <li class="item">
                            <a href="<?php echo $_item->getLink()?>">
                            <img src="<?php echo Mage::getBaseUrl('media') . $_item->getImage()?>" alt="<?php echo $_item->getTitle();?>">
                            </a>
                            </li>
                        <?php endforeach;endif;?>
                        </ul>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 hidden-xs">
                    <div class="kind-R">
                        <div class="kind-R1 left">
                         <?php $category = getCategory(89);?>
                            <a href="<?php echo $_webUrl . "lianguang-case-sony-z2-white.html"?>">
                                <img src="<?php echo $_mediaPath . "banner_slider_r_main.jpg"?>" alt="">
                            </a>
                        </div>
                        <div class="kind-R2 right">
                        <?php $category = getCategory(96);?>
                            <a href="<?php echo $category->getUrl()?>" title="<?php echo $category->getName()?>">
                                <img src="<?php echo $_mediaPath . "banner_slider_r_charger.jpg"?>" alt="">
                                <p><?php echo $category->getName()?></p>
                            </a>
                        </div>
                        <div class="kind-R2 left">
                        <?php $category = getCategory(95);?>
                            <a href="<?php echo $category->getUrl()?>" title="<?php echo $category->getName()?>">
                                <img src="<?php echo $_mediaPath . "banner_slider_r_screen.jpg"?>" alt="">
                               <p><?php echo $category->getName()?></p>
                            </a>
                        </div>
                        <div class="kind-R2 left">
                        <?php $category = getCategory(96);?>
                            <a href="<?php echo $category->getUrl()?>" title="<?php echo $category->getName()?>">
                                <img src="<?php echo $_mediaPath . "banner_slider_r_cable.jpg"?>" alt="">
                                <p><?php echo $category->getName()?></p>
                            </a>
                        </div>
                        <div class="kind-R2 right">
                        <?php $category = getCategory(99);?>
                            <a href="<?php echo $category->getUrl()?>" title="<?php echo $category->getName()?>">
                                <img src="<?php echo $_mediaPath . "banner_slider_r_holder.jpg"?>" alt="">
                                <p><?php echo $category->getName()?></p>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php */?>
<!--Mobile phone parts-->
<section class="access-wrapper phone-parts">
    <div class="access-content">
        <div class="access-box container">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 clearfix">
                    <div class="kind-Category left">
                        <h4><a href="<?php echo $_phoneParts['parent']->getUrl()?>" title="<?php echo $_phoneParts['parent']->getName()?>"><?php echo $_phoneParts['parent']->getName()?></a></h4>
                        <ul>
                        <?php 
						foreach($_phoneParts['sub'] as $_item):
							$category = getCategory($_item->getId());
						?>
                        <li><a href="<?php echo $category->getUrl()?>" title="<?php echo $category->getName();?>"><?php echo $category->getName();?></a></li>
                        <?php endforeach;?>
                        </ul>
                    </div>
                    <div class="kind-Slide right hidden-xs">
                        <ul class="kind-SlideList">
                        <!-- edit by mivec -->
                        <?php
						//edit by mivec
						if ($_slider['b']):
							foreach ($_slider['b']->getItems() as $_item) :
							//print_r($_item->gettitle());exit;
						?>
                            <li class="item">
                            <a href="<?php echo $_item->getLink()?>">
                            <img src="<?php echo Mage::getBaseUrl('media') . $_item->getImage()?>" alt="<?php echo $_item->getTitle();?>">
                            </a>
                            </li>
                        <?php endforeach;endif;?>
                        </ul>
                    </div>
                </div>
                <script type="text/javascript">	
					jQuery(document).ready(function($){
                        $('.phone-access .kind-SlideList').bxSlider({
							  auto: true,
							  speed: 800,
							  pause: 4000,			  
							  minSlides: 1,
							  infiniteLoop: true,
							  maxSlides: 1,
							  slideWidth: 349,
							  slideMargin: 0,
							  autoHover: true,
							  moveSlides:1,
							  pager: true,
							  controls:1,
                        });
						$('.phone-parts .kind-SlideList').bxSlider({
							  auto: true,
							  speed: 800,
							  pause: 4000,			  
							  minSlides: 1,
							  infiniteLoop: true,
							  maxSlides: 1,
							  slideWidth: 349,
							  slideMargin: 0,
							  autoHover: true,
							  moveSlides:1,
							  pager: true,
							  controls:1,
                        });
                    });	
                </script>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 hidden-xs">
                    <div class="kind-R">
                        <div class="kind-R1 left">
                            <a href="<?php echo $_webUrl . "best-668-screwdriver-philips-ph000.html"?>">
                                <img src="<?php echo $_mediaPath . "banner_slider_r2_repair.jpg"?>" alt="repair">
                            </a>
                        </div>
                        <div class="kind-R2 right">
                            <a href="<?php echo $_webUrl . "catalogsearch/result/?q=lcd&cat="?>" title="lcd?>">
                                <img src="<?php echo $_mediaPath . "banner_slider_r2_lcd.jpg"?>" alt="lcd">
                                <p>Lcd</p>
                            </a>
                        </div>
                        <div class="kind-R2 left">
                            <a href="<?php echo $_webUrl . "catalogsearch/result/?q=battery&cat="?>" title="Battery">
                                <img src="<?php echo $_mediaPath . "banner_slider_r2_battery.jpg"?>" alt="battery">
                                <p>Battery</p>
                            </a>
                        </div>
                        <div class="kind-R2 left">
                            <a href="<?php echo $_webUrl . "catalogsearch/result/?q=flex+cable&cat="?>" title="Flex cable">
							<img src="<?php echo $_mediaPath . "banner_slider_r2_flex_cable.jpg"?>" alt="flex cable">
                                <p>Flex cable</p>
                            </a>
                        </div>
                        <div class="kind-R2 right">
                            <a href="<?php echo $_webUrl . "catalogsearch/result/?q=camera&cat="?>" title="Camera">
                            <img src="<?php echo $_mediaPath . "banner_slider_r2_camera.jpg"?>" alt="camera">
                                <p>Camera</p>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="service" style="margin:10px 0 30px 0;">
    <div class="container">
        <div class="row">
            <div class="col-xs-4 col-sm-4 col-md-4">
                <div class="service-item">
                    <div class="icon"><img class="img-responsive" alt="services" src="http://alothemes.com/demo/supermarket/media/wysiwyg/alothemes/static/demo1/s1.png"></div>
                    <div class="info">
                        <h3>Buyer Protection</h3>
                        <p>Secure payments</p>
                        <p>Guaranteed refunds</p>
                        <p>Escrow protection on every oder</p>
                        <a href="#">Read more</a>
                    </div>
                </div>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4">
                <div class="service-item">
                    <div class="icon"><img class="img-responsive" alt="services" src="http://alothemes.com/demo/supermarket/media/wysiwyg/alothemes/static/demo1/s2.png"></div>
                    <div class="info">
                        <h3>RETURN &amp; EXCHANGE</h3>
                        <p>Wholesale products from certified</p>
                        <p>Worldwide shipping</p>
                        <p>Low prices from US $0.1</p>
                        <a href="#">Read more</a>
                    </div>
                </div>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4">
                <div class="service-item">
                    <div class="icon"><img class="img-responsive" alt="services" src="http://alothemes.com/demo/supermarket/media/wysiwyg/alothemes/static/demo1/s3.png"></div>
                    <div class="info">
                        <h3>FREE DELIVERY</h3>
                        <p>Wholesale products from certified</p>
                        <p>Worldwide shipping</p>
                        <p>Low prices from US $0.1</p>
                        <a href="#">Read more</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>