<?php
class Mivec_Support_Block_Adminhtml_Type_Grid extends Mage_Adminhtml_Block_Widget_Grid
{
    public function _construct()
    {
        parent::_construct();

        $this->setId('typeGrid');
        $this->setDefaultSort('id');
        $this->setDefaultDir('DESC');
        $this->setSaveParametersInSession(true);
    }

    protected function _prepareCollection()
    {
        $collection = Mage::getModel('support/type')->getCollection();
        $this->setCollection($collection);
        return parent::_prepareCollection();
    }

    public function _prepareColumns()
    {
        $this->addColumn("id" ,
            array(
                "header"    => "id",
                "algin"     => "left",
                "width"     => "30px",
                "index"     => "id"
            )
        );

        $this->addColumn("title" ,
            array(
                "header"    => "Title",
                "align"     => "left",
                "width"     => "200px",
                "index"     => "title"
            )
        );

        $_status = Mivec_Support_Model_Type_Status::getStatus();
        $this->addColumn("status" ,
            array(
                "header"    => "Status",
                "align"     => "left",
                "width"     => "50px",
                "type"      => "options",
                'index'     => "status",
                "options"   => $_status
            )
        );

        $this->addColumn('action',
            array(
                'header'    =>  'Action',
                'width'     => '100',
                'type'      => 'action',
                'getter'    => 'getId',
                'actions'   => array(
                    array(
                        'caption'   => 'Edit',
                        'url'       => array('base'=> '*/*/edit'),
                        'field'     => 'id'
                    )
                    ,array(
                        'caption'   => 'Delete',
                        'url'       => array('base'=> '*/*/delete'),
                        'field'     => 'id',
                        'confirm'   => 'Are you sure that the record will be delete?'
                    )
                ),
                'filter'    => false,
                'sortable'  => false,
                'index'     => 'stores',
                'is_system' => true,
            )
        );

        return parent::_prepareColumns(); // TODO: Change the autogenerated stub
    }

    public function getRowUrl($row)
    {
        //return $this->getUrl('*/*/edit', array('id' => $row->getId()));
    }
}