<div class="home-content">
    {{block type="featuredproduct/featuredproduct" name="featuredproduct" template="themevast/featuredproduct/featuredproduct.phtml" }}
    {{block type="cms/block" block_id="home1_banner_content1"}}
    {{block type="newproductslider/newproductslider" name="newproductslider" template="themevast/newproductslider/newproductslider.phtml"}}
    {{block type="cms/block" block_id="home1_banner_content2"}}
    <!-- edit by mivec -->
    {{block type="banner/home_slider" name="banner_home_slider" template="mivec/banner/slider.phtml" }}
    {{block type="bestsellerslider/bestsellerslider" name="bestsellerslider" template="themevast/bestsellerslider/bestsellerslider.phtml" }}
</div>