<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<?php
echo $this->getDesignStyles();
$package = Mage::getDesign()->getPackageName();
$theme = Mage::getDesign()->getTheme('frontend');
?>
<div class="opc-wrapper-opc design_package_<?php echo $package;?> design_theme_<?php echo $theme;?>">
	<!--add by jerry.-->
	<style type="text/css">
        .opc-wrapper-opc{position: relative;}
		#accept_item_box{display: none;
            width: 100%;
            height: 100%;
            position: fixed;
            left: 0;
            top: 0;
            z-index: 1000;
            background-color: rgba(0,0,0,0.5);  }
        .modal-content{
            display: flex;
            flex-flow: column nowrap;
            justify-content: space-between;
            width: 50%;
            max-width: 700px;
            height: 40%;
            max-height: 500px;
            margin: 100px auto;
            border-radius:10px;
            background-color:#fff;
            -webkit-animation: zoom 0.6s alternate;
            animation: zoom 0.6s alternate;
            resize: both;
            overflow: auto;
        }
        @-webkit-keyframes zoom{
            from {-webkit-transform: scale(0)}
            to {-webkit-transform: scale(1)}
        }
        @keyframes zoom{
            from {transform: scale(0)}
            to {transform: scale(1)}
        }
        .accept_close{
            color: #b7b7b7;
            font-size: 30px;
            font-weight: bold;
            margin-right: 20px;
            transition: all 0.3s;
        }
        .accept_close:hover, .accept_close:focus{
            color: #95b4ed;
            text-decoration: none;
            cursor: pointer;
        }
        .modal-body{
            padding: 10px;
            font-size: 16px;
            box-sizing:border-box;
        }
        .modal-header{
            box-sizing:border-box;
            border-bottom:1px solid #ccc;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .modal-header h4{
            font-family:"Open Sans", Arial, Helvetica;
            font-size: 16px;
            font-weight: bold;
        }
        .modal-footer{
            box-sizing:border-box;
            border-top:1px solid #ccc;
            display: flex;
            padding: 15px;
            justify-content: flex-end;
            align-items: center;
        }
        #accept_box label{padding-left: 14px;font-size: 14px;}
        .modal-footer button{
            width: 60px;
            height: 35px;
            padding: 5px;
            box-sizing: border-box;
            margin-right: 10px;
            font-size: 16px;
            color: white;
            border-radius: 5px;
            background-color: cornflowerblue;
        }
        .modal-footer button:hover, .modal-footer button:focus{
            background-color: #95b4ed;
            cursor: pointer;
        }
        @media only screen and (max-width: 700px){
            .modal-content {
                width: 80%;
            }
        }
    </style>
	<div id="accept_item_box">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Accept purchase items</h4>
                <span class="accept_close">×</span>
            </div>
            <div class="modal-body">
                <p>If you want to place order,it means that u should accept our policy at first.</p>
                <div id="accept_box"><input type="checkbox" id="accept_item"><label for="accept_item">Accept purchase items</label></div>
            </div>
            <div class="modal-footer">
                <button id="accept_cancel">close</button>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var accept_item_box = document.getElementById('accept_item_box');
        var accept_item = document.getElementById("accept_item");
        var accept_close = document.getElementsByClassName('accept_close')[0];
        var accept_cancel = document.getElementById("accept_cancel");
        accept_close.addEventListener('click',function(){
            accept_item_box.style.display = "none";
        });
        accept_cancel.addEventListener('click',function(){
            accept_item_box.style.display = "none";
        })
    </script>
    <!--add finished.-->
    <h2><?php echo $this->__('Checkout')?></h2>
	<div class="opc-menu">
	
	    <div class="clear"><?php //echo $this->getChildHtml('paypal.button')?></div>
        <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()):?>
    		<?php echo $this->getChildHtml('login');?>	
    	<?php endif;?>
    	
    	
    	<div class="review-menu-block clear">
    	  <a class="review-total open"><?php echo Mage::helper('opc')->getGrandTotal()?></a>
    	  <!--<span class="polygon"></span>-->
    	  <div id="opc-review-block">
		      <?php echo $this->_getReviewHtml()?>
		  </div>
		</div>
	   <div class="clear move-columns"></div>
	</div>
	
	<div class="clear" style="margin-bottom: 30px;"></div>
    <div class="opc-col-left">
		<form id="opc-address-form-billing" method="post">
        	<?php echo $this->getChildHtml('billing')?>
        </form>

        <form id="opc-address-form-shipping" class="hidden" method="post">
        <?php echo $this->getChildHtml('shipping')?>
        </form>

    </div>

    <div class="opc-col-center">
       <?php if (!$this->getOnepage()->getQuote()->isVirtual()):?>
    	<div class="shipping-block">
        	<h3><?php echo $this->__('Shipping Method')?></h3>
        	<div id="shipping-block-methods">
				<?php echo $this->getChildHtml('shipping_method');//$this->_getShippingMethodsHtml();?>
			</div>
		</div>
		<?php endif;?>

		<?php if(Mage::helper('opc')->isShowDiscount()):?>
		<div class="discount-block">
			<h3><?php echo $this->__('Discount Codes')?><span class='expand_plus'></span></h3>
			<div  class="collapse-block hidden">
			     <?php echo $this->getChildhtml('coupon');?>
			</div>
		</div>
		<?php endif;?>

		<?php if(Mage::helper('opc')->isShowComment()):?>
			<?php echo $this->getChildhtml('customer.comment');?>
		<?php endif;?>
    </div>

    <div class="opc-col-right">
		<div class="payment-block <?php if ($this->getOnepage()->getQuote()->isVirtual()):?>clear-margin<?php endif;?>">
			<h3><?php echo $this->__('Payment Method')?></h3>
			<?php echo $this->getChildHtml('payment')//$this->_getPaymentMethodsHtml();?>
		</div>

        <?php if (Mage::getConfig()->getModuleConfig('IWD_OnepageCheckoutSignature')->is('active', 'true')): ?>
            <div class="signature-block">
                <h3><?php echo $this->__('Signature')?><span class='expand_plus'></span></h3>
                <div  class="collapse-block hidden">
                    <?php echo $this->getChildhtml('opcsignature');?>
                </div>
            </div>
        <?php endif;?>

		<div class="opc-review-actions" id="checkout-review-submit">
		      <h5 class="grand_total"><?php echo $this->__('Grand Total')?><?php echo Mage::helper('opc')->getGrandTotal()?></h5>
		      <?php echo $this->getChildHtml('agreements')?>
		      <?php echo $this->getChildHtml('opc.newsletters');?>
		      <button type="button" title="<?php echo $this->__('Place Order Now') ?>" class="button btn-checkout opc-btn-checkout"><span><span><?php echo $this->__('Place Order Now') ?></span></span></button>
		</div>
    </div>
</div>
<script>
	var vopc = '<?php echo Mage::getConfig()->getModuleConfig("IWD_Opc")->version;?>';
	IWD.OPC.Checkout.config = '<?php echo $this->getJsonConfig()?>';
	<?php if ($this->getOnepage()->getQuote()->isVirtual()):?>
	IWD.OPC.Checkout.isVirtual = true;
	<?php endif;?>	 
</script>

<div id="agree_error" style="display:none !important;"><?php echo $this->__('Please agree to all the terms and conditions before placing the order.');?></div>
<div id="pssm_msg" style="display:none !important;"><?php echo $this->__('Please specify shipping method');?></div>
<div class="opc-ajax-loader">
	<div id="floatingCirclesG">
		<div class="f_circleG" id="frotateG_01"></div>
		<div class="f_circleG" id="frotateG_02"></div>
		<div class="f_circleG" id="frotateG_03"></div>
		<div class="f_circleG" id="frotateG_04"></div>
		<div class="f_circleG" id="frotateG_05"></div>
		<div class="f_circleG" id="frotateG_06"></div>
		<div class="f_circleG" id="frotateG_07"></div>
		<div class="f_circleG" id="frotateG_08"></div>
	</div>
</div>
<div class="opc-message-wrapper design_package_<?php echo $package;?> design_theme_<?php echo $theme;?>">
	
	<div class="opc-messages">
		<a class="close-message-wrapper"></a>
		<div class="opc-message-container"></div>
		<div class="opc-messages-action"><button class="button"><span><span><?php echo $this->__('Close')?></span></span></button></div>
	</div>
</div>