<div class="nav-vcontainer hidden-xs hidden-sm">
    <div class="nav-inner">
        <div class="vmegamenu-title"><h2><i class="fa fa-bars"></i><?php echo $this->__('Categories') ?></h2></div>
        <div class="vmegamenu-contain">
            <div id="nav_vmegamenu" class="nav_vmegamenu">
                <?php $megamenu =  $this->getLayout()->createBlock('megamenu/megamenu'); ?>       
                <?php //echo $megamenu->drawMegamenuHome(); ?>
                <?php echo $megamenu->drawMegamenuMain(); ?>        
                <?php //echo $megamenu->drawMegamenuExtra(); ?>
                <?php //echo $megamenu->drawMegamenuLink(); ?>
            </div>
        </div>
		<!-- add by jerry,05/22-->
    </div>
    <script type="text/javascript">
        //<![CDATA[
        var MEGAMENU_EFFECT = <?php echo (int)Mage::getStoreConfig('megamenu/general/effect')?>;
        
        //]]>
    </script>
	<script type="text/javascript">
			//add by jerry
			jQuery(document).ready(function($){
				/*
				*set viewmore
				*/
				$('.itemMenu.level2>div.itemSubMenu.level2').remove();
				$('.itemMenu.level1').each(function(){
					var $itemMenu1 = $(this);
					var countA = $itemMenu1.find(".itemMenuName.level1").length;
					for(var i = 0;i<countA;i++){
						setHref(i);
					}
					function setHref(count){
						var len = $itemMenu1.children(".itemSubMenu.level1").eq(count).find(".itemMenu.level2>a").length;
						//get url and add to view more
						if(len>=8){
							var tmpHref = $itemMenu1.find("a.itemMenuName.level1").eq(count).attr("href");
							$itemMenu1.find(".itemMenu.level2").eq(count).append("<p><a class='viewmore' href='"+tmpHref+"'>view more</a></p>");
						}
					}
				});
				/*
				*set menu item hide
				*/
				$(".itemSubMenu").each(function(){
					$(this).find(".itemMenu>a.itemMenuName:gt(7)").css({'display':'none'}).remove();
				});
			});
	</script>
</div>
