<?php
$webUrl = Mage::getBaseUrl();
$skinUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);
?>

<!--img src="<?php //echo $this->getSkinUrl('images/home/bestseller.jpg');?>" />-->
<!--best sellers begin-->
<div class="seller-Box clearfix">
	<div class="seller-Head">
		<h3>Best Sellers</h3>
	</div>
	<div class="seller-Main row clearfix">
		<div class="col-xs-12 col-lg-7 col-md-7 hidden-xs">
			<div class="seller-L1 left">
			<a href="<?php echo $webUrl."for-oneplus-x-lcd-white.html"?>">
				<img src="<?php echo $skinUrl?>/frontend/tv_bigboom_package/tv_bigboom1/images/new_add/seller/seller-L1.jpg" alt="">
				<i class="imgText">LCD</i>
			</a>
			</div>
			<div class="seller-L2 left">
				<a href="<?php echo $webUrl."g-sp-samsung-s8-plus-super-glass-gold.html"?>">
					<img src="<?php echo $skinUrl?>/frontend/tv_bigboom_package/tv_bigboom1/images/new_add/seller/seller-L2.jpg" alt="">
					<i class="imgText">Glass</i>
				</a>
			</div>
		</div>
		<div class="col-xs-12 col-lg-5 col-md-5">
			<div class="seller-L3">
				<a href="<?php echo $webUrl."iphone-6-wifi-ic.html"?>">
					<img src="<?php echo $skinUrl?>/frontend/tv_bigboom_package/tv_bigboom1/images/new_add/seller/seller-L31.jpg" alt="">
					<i class="imgText it1">IC</i>
				</a>
				<a href="<?php echo $webUrl."g-sp-leather-case-with-wallet-for-iphone-7.html"?>">
					<img src="<?php echo $skinUrl?>/frontend/tv_bigboom_package/tv_bigboom1/images/new_add/seller/seller-L32.jpg" alt="">
					<i class="imgText it2">Case</i>
				</a>
				<a href="<?php echo $webUrl."iphone-6-original-battery.html"?>">
					<img src="<?php echo $skinUrl?>/frontend/tv_bigboom_package/tv_bigboom1/images/new_add/seller/seller-L33.jpg" alt="">
					<i class="imgText it3">Battery</i>
				</a>
				<a href="<?php echo $webUrl."samsung-sm-g930f-s7-charge-flex.html"?>">
					<img src="<?php echo $skinUrl?>/frontend/tv_bigboom_package/tv_bigboom1/images/new_add/seller/seller-L34.jpg" alt="">
					<i class="imgText it4">Flex</i>
				</a>
			</div>
		</div>
	</div>
</div>
